indexing-settings:
  sites:
    - url: https://nekdo.ru
      name: nekdo.ru
    - url: http://www.playback.ru
      name: www.playback.ru



server:
  port: 8080

spring:
  datasource:
    username: root
    password: testtest
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
       ddl-auto: update

logging:
  level:
    org.hibernate: "INFO"

